//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace BRMONITOR.rpt {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("NewDataSet")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class NewDataSet : global::System.Data.DataSet {
        
        private TableDataTable tableTable;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public NewDataSet() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected NewDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["Table"] != null)) {
                    base.Tables.Add(new TableDataTable(ds.Tables["Table"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public TableDataTable Table {
            get {
                return this.tableTable;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            NewDataSet cln = ((NewDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["Table"] != null)) {
                    base.Tables.Add(new TableDataTable(ds.Tables["Table"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableTable = ((TableDataTable)(base.Tables["Table"]));
            if ((initTable == true)) {
                if ((this.tableTable != null)) {
                    this.tableTable.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "NewDataSet";
            this.Prefix = "";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableTable = new TableDataTable();
            base.Tables.Add(this.tableTable);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeTable() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            NewDataSet ds = new NewDataSet();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void TableRowChangeEventHandler(object sender, TableRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class TableDataTable : global::System.Data.TypedTableBase<TableRow> {
            
            private global::System.Data.DataColumn columnNGAY_32A;
            
            private global::System.Data.DataColumn columnRM_NUMBER;
            
            private global::System.Data.DataColumn columnSENDER;
            
            private global::System.Data.DataColumn columnRECEIVER;
            
            private global::System.Data.DataColumn columnSENDERNAME;
            
            private global::System.Data.DataColumn columnRECEIVERNAME;
            
            private global::System.Data.DataColumn columnSOLENH;
            
            private global::System.Data.DataColumn columnREF_NO;
            
            private global::System.Data.DataColumn columnreceiving_time;
            
            private global::System.Data.DataColumn columnsending_time;
            
            private global::System.Data.DataColumn columnNGUOIRALENH;
            
            private global::System.Data.DataColumn columnTKNGUOIRALENH;
            
            private global::System.Data.DataColumn columnDCNGUOIRALENH;
            
            private global::System.Data.DataColumn columnNGUOIHUONG;
            
            private global::System.Data.DataColumn columnTK_HUONG;
            
            private global::System.Data.DataColumn columnDIACHI;
            
            private global::System.Data.DataColumn columnCONTENT;
            
            private global::System.Data.DataColumn columnTK_GHINO;
            
            private global::System.Data.DataColumn columnTEN_TK;
            
            private global::System.Data.DataColumn columnCCY;
            
            private global::System.Data.DataColumn columnORG_AMOUNT;
            
            private global::System.Data.DataColumn columnLOAIPHI;
            
            private global::System.Data.DataColumn columnTIENPHI;
            
            private global::System.Data.DataColumn columnDVTIENPHI;
            
            private global::System.Data.DataColumn columnNH_HUONG;
            
            private global::System.Data.DataColumn columnBRNAME;
            
            private global::System.Data.DataColumn columnTellername;
            
            private global::System.Data.DataColumn columnCCYNAME;
            
            private global::System.Data.DataColumn columnTellerID;
            
            private global::System.Data.DataColumn columnSIBS_TELLERID;
            
            private global::System.Data.DataColumn columnGRPID;
            
            private global::System.Data.DataColumn columnMSGDIR;
            
            private global::System.Data.DataColumn columnPRINTED;
            
            private global::System.Data.DataColumn columnPRINT_TIME;
            
            private global::System.Data.DataColumn columnTRANSMIT_TIME;
            
            private global::System.Data.DataColumn columnCONFIRM_TIME;
            
            private global::System.Data.DataColumn columnAMOUNT;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TableDataTable() {
                this.TableName = "Table";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal TableDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected TableDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn NGAY_32AColumn {
                get {
                    return this.columnNGAY_32A;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn RM_NUMBERColumn {
                get {
                    return this.columnRM_NUMBER;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SENDERColumn {
                get {
                    return this.columnSENDER;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn RECEIVERColumn {
                get {
                    return this.columnRECEIVER;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SENDERNAMEColumn {
                get {
                    return this.columnSENDERNAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn RECEIVERNAMEColumn {
                get {
                    return this.columnRECEIVERNAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SOLENHColumn {
                get {
                    return this.columnSOLENH;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn REF_NOColumn {
                get {
                    return this.columnREF_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn receiving_timeColumn {
                get {
                    return this.columnreceiving_time;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn sending_timeColumn {
                get {
                    return this.columnsending_time;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn NGUOIRALENHColumn {
                get {
                    return this.columnNGUOIRALENH;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TKNGUOIRALENHColumn {
                get {
                    return this.columnTKNGUOIRALENH;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DCNGUOIRALENHColumn {
                get {
                    return this.columnDCNGUOIRALENH;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn NGUOIHUONGColumn {
                get {
                    return this.columnNGUOIHUONG;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TK_HUONGColumn {
                get {
                    return this.columnTK_HUONG;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DIACHIColumn {
                get {
                    return this.columnDIACHI;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CONTENTColumn {
                get {
                    return this.columnCONTENT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TK_GHINOColumn {
                get {
                    return this.columnTK_GHINO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TEN_TKColumn {
                get {
                    return this.columnTEN_TK;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CCYColumn {
                get {
                    return this.columnCCY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ORG_AMOUNTColumn {
                get {
                    return this.columnORG_AMOUNT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn LOAIPHIColumn {
                get {
                    return this.columnLOAIPHI;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TIENPHIColumn {
                get {
                    return this.columnTIENPHI;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DVTIENPHIColumn {
                get {
                    return this.columnDVTIENPHI;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn NH_HUONGColumn {
                get {
                    return this.columnNH_HUONG;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BRNAMEColumn {
                get {
                    return this.columnBRNAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TellernameColumn {
                get {
                    return this.columnTellername;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CCYNAMEColumn {
                get {
                    return this.columnCCYNAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TellerIDColumn {
                get {
                    return this.columnTellerID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SIBS_TELLERIDColumn {
                get {
                    return this.columnSIBS_TELLERID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn GRPIDColumn {
                get {
                    return this.columnGRPID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn MSGDIRColumn {
                get {
                    return this.columnMSGDIR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PRINTEDColumn {
                get {
                    return this.columnPRINTED;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PRINT_TIMEColumn {
                get {
                    return this.columnPRINT_TIME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TRANSMIT_TIMEColumn {
                get {
                    return this.columnTRANSMIT_TIME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CONFIRM_TIMEColumn {
                get {
                    return this.columnCONFIRM_TIME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn AMOUNTColumn {
                get {
                    return this.columnAMOUNT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TableRow this[int index] {
                get {
                    return ((TableRow)(this.Rows[index]));
                }
            }
            
            public event TableRowChangeEventHandler TableRowChanging;
            
            public event TableRowChangeEventHandler TableRowChanged;
            
            public event TableRowChangeEventHandler TableRowDeleting;
            
            public event TableRowChangeEventHandler TableRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddTableRow(TableRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TableRow AddTableRow(
                        string NGAY_32A, 
                        System.DateTime RM_NUMBER, 
                        string SENDER, 
                        string RECEIVER, 
                        string SENDERNAME, 
                        string RECEIVERNAME, 
                        string SOLENH, 
                        string REF_NO, 
                        string receiving_time, 
                        string sending_time, 
                        string NGUOIRALENH, 
                        string TKNGUOIRALENH, 
                        string DCNGUOIRALENH, 
                        string NGUOIHUONG, 
                        string TK_HUONG, 
                        string DIACHI, 
                        string CONTENT, 
                        string TK_GHINO, 
                        string TEN_TK, 
                        string CCY, 
                        string ORG_AMOUNT, 
                        string LOAIPHI, 
                        string TIENPHI, 
                        string DVTIENPHI, 
                        string NH_HUONG, 
                        System.DateTime BRNAME, 
                        System.DateTime Tellername, 
                        decimal CCYNAME, 
                        string TellerID, 
                        string SIBS_TELLERID, 
                        string GRPID, 
                        string MSGDIR, 
                        string PRINTED, 
                        string PRINT_TIME, 
                        string TRANSMIT_TIME, 
                        string CONFIRM_TIME, 
                        string AMOUNT) {
                TableRow rowTableRow = ((TableRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        NGAY_32A,
                        RM_NUMBER,
                        SENDER,
                        RECEIVER,
                        SENDERNAME,
                        RECEIVERNAME,
                        SOLENH,
                        REF_NO,
                        receiving_time,
                        sending_time,
                        NGUOIRALENH,
                        TKNGUOIRALENH,
                        DCNGUOIRALENH,
                        NGUOIHUONG,
                        TK_HUONG,
                        DIACHI,
                        CONTENT,
                        TK_GHINO,
                        TEN_TK,
                        CCY,
                        ORG_AMOUNT,
                        LOAIPHI,
                        TIENPHI,
                        DVTIENPHI,
                        NH_HUONG,
                        BRNAME,
                        Tellername,
                        CCYNAME,
                        TellerID,
                        SIBS_TELLERID,
                        GRPID,
                        MSGDIR,
                        PRINTED,
                        PRINT_TIME,
                        TRANSMIT_TIME,
                        CONFIRM_TIME,
                        AMOUNT};
                rowTableRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowTableRow);
                return rowTableRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                TableDataTable cln = ((TableDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new TableDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnNGAY_32A = base.Columns["NGAY_32A"];
                this.columnRM_NUMBER = base.Columns["RM_NUMBER"];
                this.columnSENDER = base.Columns["SENDER"];
                this.columnRECEIVER = base.Columns["RECEIVER"];
                this.columnSENDERNAME = base.Columns["SENDERNAME"];
                this.columnRECEIVERNAME = base.Columns["RECEIVERNAME"];
                this.columnSOLENH = base.Columns["SOLENH"];
                this.columnREF_NO = base.Columns["REF_NO"];
                this.columnreceiving_time = base.Columns["receiving_time"];
                this.columnsending_time = base.Columns["sending_time"];
                this.columnNGUOIRALENH = base.Columns["NGUOIRALENH"];
                this.columnTKNGUOIRALENH = base.Columns["TKNGUOIRALENH"];
                this.columnDCNGUOIRALENH = base.Columns["DCNGUOIRALENH"];
                this.columnNGUOIHUONG = base.Columns["NGUOIHUONG"];
                this.columnTK_HUONG = base.Columns["TK_HUONG"];
                this.columnDIACHI = base.Columns["DIACHI"];
                this.columnCONTENT = base.Columns["CONTENT"];
                this.columnTK_GHINO = base.Columns["TK_GHINO"];
                this.columnTEN_TK = base.Columns["TEN_TK"];
                this.columnCCY = base.Columns["CCY"];
                this.columnORG_AMOUNT = base.Columns["ORG_AMOUNT"];
                this.columnLOAIPHI = base.Columns["LOAIPHI"];
                this.columnTIENPHI = base.Columns["TIENPHI"];
                this.columnDVTIENPHI = base.Columns["DVTIENPHI"];
                this.columnNH_HUONG = base.Columns["NH_HUONG"];
                this.columnBRNAME = base.Columns["BRNAME"];
                this.columnTellername = base.Columns["Tellername"];
                this.columnCCYNAME = base.Columns["CCYNAME"];
                this.columnTellerID = base.Columns["TellerID"];
                this.columnSIBS_TELLERID = base.Columns["SIBS_TELLERID"];
                this.columnGRPID = base.Columns["GRPID"];
                this.columnMSGDIR = base.Columns["MSGDIR"];
                this.columnPRINTED = base.Columns["PRINTED"];
                this.columnPRINT_TIME = base.Columns["PRINT_TIME"];
                this.columnTRANSMIT_TIME = base.Columns["TRANSMIT_TIME"];
                this.columnCONFIRM_TIME = base.Columns["CONFIRM_TIME"];
                this.columnAMOUNT = base.Columns["AMOUNT"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnNGAY_32A = new global::System.Data.DataColumn("NGAY_32A", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNGAY_32A);
                this.columnRM_NUMBER = new global::System.Data.DataColumn("RM_NUMBER", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRM_NUMBER);
                this.columnSENDER = new global::System.Data.DataColumn("SENDER", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSENDER);
                this.columnRECEIVER = new global::System.Data.DataColumn("RECEIVER", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRECEIVER);
                this.columnSENDERNAME = new global::System.Data.DataColumn("SENDERNAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSENDERNAME);
                this.columnRECEIVERNAME = new global::System.Data.DataColumn("RECEIVERNAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRECEIVERNAME);
                this.columnSOLENH = new global::System.Data.DataColumn("SOLENH", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSOLENH);
                this.columnREF_NO = new global::System.Data.DataColumn("REF_NO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnREF_NO);
                this.columnreceiving_time = new global::System.Data.DataColumn("receiving_time", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnreceiving_time);
                this.columnsending_time = new global::System.Data.DataColumn("sending_time", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsending_time);
                this.columnNGUOIRALENH = new global::System.Data.DataColumn("NGUOIRALENH", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNGUOIRALENH);
                this.columnTKNGUOIRALENH = new global::System.Data.DataColumn("TKNGUOIRALENH", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTKNGUOIRALENH);
                this.columnDCNGUOIRALENH = new global::System.Data.DataColumn("DCNGUOIRALENH", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDCNGUOIRALENH);
                this.columnNGUOIHUONG = new global::System.Data.DataColumn("NGUOIHUONG", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNGUOIHUONG);
                this.columnTK_HUONG = new global::System.Data.DataColumn("TK_HUONG", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTK_HUONG);
                this.columnDIACHI = new global::System.Data.DataColumn("DIACHI", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDIACHI);
                this.columnCONTENT = new global::System.Data.DataColumn("CONTENT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCONTENT);
                this.columnTK_GHINO = new global::System.Data.DataColumn("TK_GHINO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTK_GHINO);
                this.columnTEN_TK = new global::System.Data.DataColumn("TEN_TK", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTEN_TK);
                this.columnCCY = new global::System.Data.DataColumn("CCY", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCCY);
                this.columnORG_AMOUNT = new global::System.Data.DataColumn("ORG_AMOUNT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnORG_AMOUNT);
                this.columnLOAIPHI = new global::System.Data.DataColumn("LOAIPHI", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLOAIPHI);
                this.columnTIENPHI = new global::System.Data.DataColumn("TIENPHI", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTIENPHI);
                this.columnDVTIENPHI = new global::System.Data.DataColumn("DVTIENPHI", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDVTIENPHI);
                this.columnNH_HUONG = new global::System.Data.DataColumn("NH_HUONG", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNH_HUONG);
                this.columnBRNAME = new global::System.Data.DataColumn("BRNAME", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBRNAME);
                this.columnTellername = new global::System.Data.DataColumn("Tellername", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTellername);
                this.columnCCYNAME = new global::System.Data.DataColumn("CCYNAME", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCCYNAME);
                this.columnTellerID = new global::System.Data.DataColumn("TellerID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTellerID);
                this.columnSIBS_TELLERID = new global::System.Data.DataColumn("SIBS_TELLERID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSIBS_TELLERID);
                this.columnGRPID = new global::System.Data.DataColumn("GRPID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnGRPID);
                this.columnMSGDIR = new global::System.Data.DataColumn("MSGDIR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMSGDIR);
                this.columnPRINTED = new global::System.Data.DataColumn("PRINTED", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPRINTED);
                this.columnPRINT_TIME = new global::System.Data.DataColumn("PRINT_TIME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPRINT_TIME);
                this.columnTRANSMIT_TIME = new global::System.Data.DataColumn("TRANSMIT_TIME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTRANSMIT_TIME);
                this.columnCONFIRM_TIME = new global::System.Data.DataColumn("CONFIRM_TIME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCONFIRM_TIME);
                this.columnAMOUNT = new global::System.Data.DataColumn("AMOUNT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAMOUNT);
                this.ExtendedProperties.Add("Generator_RowClassName", "TableRow");
                this.ExtendedProperties.Add("Generator_RowEvArgName", "TableRowChangeEvent");
                this.ExtendedProperties.Add("Generator_RowEvHandlerName", "TableRowChangeEventHandler");
                this.ExtendedProperties.Add("Generator_TableClassName", "TableDataTable");
                this.ExtendedProperties.Add("Generator_TablePropName", "Table");
                this.ExtendedProperties.Add("Generator_TableVarName", "tableTable");
                this.ExtendedProperties.Add("Generator_UserTableName", "Table");
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TableRow NewTableRow() {
                return ((TableRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new TableRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(TableRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.TableRowChanged != null)) {
                    this.TableRowChanged(this, new TableRowChangeEvent(((TableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.TableRowChanging != null)) {
                    this.TableRowChanging(this, new TableRowChangeEvent(((TableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.TableRowDeleted != null)) {
                    this.TableRowDeleted(this, new TableRowChangeEvent(((TableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.TableRowDeleting != null)) {
                    this.TableRowDeleting(this, new TableRowChangeEvent(((TableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveTableRow(TableRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                NewDataSet ds = new NewDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "TableDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class TableRow : global::System.Data.DataRow {
            
            private TableDataTable tableTable;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal TableRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableTable = ((TableDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string NGAY_32A {
                get {
                    try {
                        return ((string)(this[this.tableTable.NGAY_32AColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NGAY_32A\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.NGAY_32AColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime RM_NUMBER {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableTable.RM_NUMBERColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RM_NUMBER\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.RM_NUMBERColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SENDER {
                get {
                    try {
                        return ((string)(this[this.tableTable.SENDERColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SENDER\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.SENDERColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string RECEIVER {
                get {
                    try {
                        return ((string)(this[this.tableTable.RECEIVERColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RECEIVER\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.RECEIVERColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SENDERNAME {
                get {
                    try {
                        return ((string)(this[this.tableTable.SENDERNAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SENDERNAME\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.SENDERNAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string RECEIVERNAME {
                get {
                    try {
                        return ((string)(this[this.tableTable.RECEIVERNAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RECEIVERNAME\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.RECEIVERNAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SOLENH {
                get {
                    try {
                        return ((string)(this[this.tableTable.SOLENHColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SOLENH\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.SOLENHColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string REF_NO {
                get {
                    try {
                        return ((string)(this[this.tableTable.REF_NOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'REF_NO\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.REF_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string receiving_time {
                get {
                    try {
                        return ((string)(this[this.tableTable.receiving_timeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'receiving_time\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.receiving_timeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string sending_time {
                get {
                    try {
                        return ((string)(this[this.tableTable.sending_timeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'sending_time\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.sending_timeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string NGUOIRALENH {
                get {
                    try {
                        return ((string)(this[this.tableTable.NGUOIRALENHColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NGUOIRALENH\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.NGUOIRALENHColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TKNGUOIRALENH {
                get {
                    try {
                        return ((string)(this[this.tableTable.TKNGUOIRALENHColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TKNGUOIRALENH\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.TKNGUOIRALENHColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DCNGUOIRALENH {
                get {
                    try {
                        return ((string)(this[this.tableTable.DCNGUOIRALENHColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DCNGUOIRALENH\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.DCNGUOIRALENHColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string NGUOIHUONG {
                get {
                    try {
                        return ((string)(this[this.tableTable.NGUOIHUONGColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NGUOIHUONG\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.NGUOIHUONGColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TK_HUONG {
                get {
                    try {
                        return ((string)(this[this.tableTable.TK_HUONGColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TK_HUONG\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.TK_HUONGColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DIACHI {
                get {
                    try {
                        return ((string)(this[this.tableTable.DIACHIColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DIACHI\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.DIACHIColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CONTENT {
                get {
                    try {
                        return ((string)(this[this.tableTable.CONTENTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CONTENT\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.CONTENTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TK_GHINO {
                get {
                    try {
                        return ((string)(this[this.tableTable.TK_GHINOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TK_GHINO\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.TK_GHINOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TEN_TK {
                get {
                    try {
                        return ((string)(this[this.tableTable.TEN_TKColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TEN_TK\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.TEN_TKColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CCY {
                get {
                    try {
                        return ((string)(this[this.tableTable.CCYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CCY\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.CCYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ORG_AMOUNT {
                get {
                    try {
                        return ((string)(this[this.tableTable.ORG_AMOUNTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ORG_AMOUNT\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.ORG_AMOUNTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string LOAIPHI {
                get {
                    try {
                        return ((string)(this[this.tableTable.LOAIPHIColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'LOAIPHI\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.LOAIPHIColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TIENPHI {
                get {
                    try {
                        return ((string)(this[this.tableTable.TIENPHIColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TIENPHI\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.TIENPHIColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DVTIENPHI {
                get {
                    try {
                        return ((string)(this[this.tableTable.DVTIENPHIColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DVTIENPHI\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.DVTIENPHIColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string NH_HUONG {
                get {
                    try {
                        return ((string)(this[this.tableTable.NH_HUONGColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NH_HUONG\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.NH_HUONGColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime BRNAME {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableTable.BRNAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BRNAME\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.BRNAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime Tellername {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableTable.TellernameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Tellername\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.TellernameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal CCYNAME {
                get {
                    try {
                        return ((decimal)(this[this.tableTable.CCYNAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CCYNAME\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.CCYNAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TellerID {
                get {
                    try {
                        return ((string)(this[this.tableTable.TellerIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TellerID\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.TellerIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SIBS_TELLERID {
                get {
                    try {
                        return ((string)(this[this.tableTable.SIBS_TELLERIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SIBS_TELLERID\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.SIBS_TELLERIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string GRPID {
                get {
                    try {
                        return ((string)(this[this.tableTable.GRPIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'GRPID\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.GRPIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string MSGDIR {
                get {
                    try {
                        return ((string)(this[this.tableTable.MSGDIRColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'MSGDIR\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.MSGDIRColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PRINTED {
                get {
                    try {
                        return ((string)(this[this.tableTable.PRINTEDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PRINTED\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.PRINTEDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PRINT_TIME {
                get {
                    try {
                        return ((string)(this[this.tableTable.PRINT_TIMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PRINT_TIME\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.PRINT_TIMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TRANSMIT_TIME {
                get {
                    try {
                        return ((string)(this[this.tableTable.TRANSMIT_TIMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TRANSMIT_TIME\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.TRANSMIT_TIMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CONFIRM_TIME {
                get {
                    try {
                        return ((string)(this[this.tableTable.CONFIRM_TIMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CONFIRM_TIME\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.CONFIRM_TIMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string AMOUNT {
                get {
                    try {
                        return ((string)(this[this.tableTable.AMOUNTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'AMOUNT\' in table \'Table\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTable.AMOUNTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNGAY_32ANull() {
                return this.IsNull(this.tableTable.NGAY_32AColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNGAY_32ANull() {
                this[this.tableTable.NGAY_32AColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRM_NUMBERNull() {
                return this.IsNull(this.tableTable.RM_NUMBERColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRM_NUMBERNull() {
                this[this.tableTable.RM_NUMBERColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSENDERNull() {
                return this.IsNull(this.tableTable.SENDERColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSENDERNull() {
                this[this.tableTable.SENDERColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRECEIVERNull() {
                return this.IsNull(this.tableTable.RECEIVERColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRECEIVERNull() {
                this[this.tableTable.RECEIVERColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSENDERNAMENull() {
                return this.IsNull(this.tableTable.SENDERNAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSENDERNAMENull() {
                this[this.tableTable.SENDERNAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRECEIVERNAMENull() {
                return this.IsNull(this.tableTable.RECEIVERNAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRECEIVERNAMENull() {
                this[this.tableTable.RECEIVERNAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSOLENHNull() {
                return this.IsNull(this.tableTable.SOLENHColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSOLENHNull() {
                this[this.tableTable.SOLENHColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsREF_NONull() {
                return this.IsNull(this.tableTable.REF_NOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetREF_NONull() {
                this[this.tableTable.REF_NOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isreceiving_timeNull() {
                return this.IsNull(this.tableTable.receiving_timeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setreceiving_timeNull() {
                this[this.tableTable.receiving_timeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Issending_timeNull() {
                return this.IsNull(this.tableTable.sending_timeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setsending_timeNull() {
                this[this.tableTable.sending_timeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNGUOIRALENHNull() {
                return this.IsNull(this.tableTable.NGUOIRALENHColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNGUOIRALENHNull() {
                this[this.tableTable.NGUOIRALENHColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTKNGUOIRALENHNull() {
                return this.IsNull(this.tableTable.TKNGUOIRALENHColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTKNGUOIRALENHNull() {
                this[this.tableTable.TKNGUOIRALENHColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDCNGUOIRALENHNull() {
                return this.IsNull(this.tableTable.DCNGUOIRALENHColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDCNGUOIRALENHNull() {
                this[this.tableTable.DCNGUOIRALENHColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNGUOIHUONGNull() {
                return this.IsNull(this.tableTable.NGUOIHUONGColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNGUOIHUONGNull() {
                this[this.tableTable.NGUOIHUONGColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTK_HUONGNull() {
                return this.IsNull(this.tableTable.TK_HUONGColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTK_HUONGNull() {
                this[this.tableTable.TK_HUONGColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDIACHINull() {
                return this.IsNull(this.tableTable.DIACHIColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDIACHINull() {
                this[this.tableTable.DIACHIColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCONTENTNull() {
                return this.IsNull(this.tableTable.CONTENTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCONTENTNull() {
                this[this.tableTable.CONTENTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTK_GHINONull() {
                return this.IsNull(this.tableTable.TK_GHINOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTK_GHINONull() {
                this[this.tableTable.TK_GHINOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTEN_TKNull() {
                return this.IsNull(this.tableTable.TEN_TKColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTEN_TKNull() {
                this[this.tableTable.TEN_TKColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCCYNull() {
                return this.IsNull(this.tableTable.CCYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCCYNull() {
                this[this.tableTable.CCYColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsORG_AMOUNTNull() {
                return this.IsNull(this.tableTable.ORG_AMOUNTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetORG_AMOUNTNull() {
                this[this.tableTable.ORG_AMOUNTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsLOAIPHINull() {
                return this.IsNull(this.tableTable.LOAIPHIColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetLOAIPHINull() {
                this[this.tableTable.LOAIPHIColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTIENPHINull() {
                return this.IsNull(this.tableTable.TIENPHIColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTIENPHINull() {
                this[this.tableTable.TIENPHIColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDVTIENPHINull() {
                return this.IsNull(this.tableTable.DVTIENPHIColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDVTIENPHINull() {
                this[this.tableTable.DVTIENPHIColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNH_HUONGNull() {
                return this.IsNull(this.tableTable.NH_HUONGColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNH_HUONGNull() {
                this[this.tableTable.NH_HUONGColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsBRNAMENull() {
                return this.IsNull(this.tableTable.BRNAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetBRNAMENull() {
                this[this.tableTable.BRNAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTellernameNull() {
                return this.IsNull(this.tableTable.TellernameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTellernameNull() {
                this[this.tableTable.TellernameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCCYNAMENull() {
                return this.IsNull(this.tableTable.CCYNAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCCYNAMENull() {
                this[this.tableTable.CCYNAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTellerIDNull() {
                return this.IsNull(this.tableTable.TellerIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTellerIDNull() {
                this[this.tableTable.TellerIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSIBS_TELLERIDNull() {
                return this.IsNull(this.tableTable.SIBS_TELLERIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSIBS_TELLERIDNull() {
                this[this.tableTable.SIBS_TELLERIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsGRPIDNull() {
                return this.IsNull(this.tableTable.GRPIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetGRPIDNull() {
                this[this.tableTable.GRPIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsMSGDIRNull() {
                return this.IsNull(this.tableTable.MSGDIRColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetMSGDIRNull() {
                this[this.tableTable.MSGDIRColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPRINTEDNull() {
                return this.IsNull(this.tableTable.PRINTEDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPRINTEDNull() {
                this[this.tableTable.PRINTEDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPRINT_TIMENull() {
                return this.IsNull(this.tableTable.PRINT_TIMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPRINT_TIMENull() {
                this[this.tableTable.PRINT_TIMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTRANSMIT_TIMENull() {
                return this.IsNull(this.tableTable.TRANSMIT_TIMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTRANSMIT_TIMENull() {
                this[this.tableTable.TRANSMIT_TIMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCONFIRM_TIMENull() {
                return this.IsNull(this.tableTable.CONFIRM_TIMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCONFIRM_TIMENull() {
                this[this.tableTable.CONFIRM_TIMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsAMOUNTNull() {
                return this.IsNull(this.tableTable.AMOUNTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetAMOUNTNull() {
                this[this.tableTable.AMOUNTColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class TableRowChangeEvent : global::System.EventArgs {
            
            private TableRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TableRowChangeEvent(TableRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public TableRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591