
insert into MENU (ID, MENUID, PARENTID, CAPTION, ASSEMBLY, ASSEMBLYFILE, METHOD, ENABLE, CTRL, ALT, KEY, GWTYPE, OPTIONDATA, TOOLTIPTEXT, ORDERMENU)
values (1160, '4050', '4003', 'IBPS Tad Map', 'BR.BRIBPS.frmIBPS_TAD_MAP', 'BRIBPS.dll', 'ShowDialog', 1, 0, 1, 'B', 'GWSYSTEM', null, null, 3);

