

BEGIN
  DBMS_SCHEDULER.set_attribute(
    'IBPS_JOB_DBLINK_INQUIRYOUT',
    'JOB_ACTION',
    'GW_PK_IBPS_DBLINK_CITAD_2_1.GET_IBPS_CONTENT');
END;
/
BEGIN
  DBMS_SCHEDULER.set_attribute(
    'IBPS_DBLINK_Q_CONVERTOUT',
    'JOB_ACTION',
    'GW_PK_IBPS_DBLINK_CITAD_2_1.SendMessage_DBLINKD');
END;
/
BEGIN
  DBMS_SCHEDULER.set_attribute(
    'IBPS_JOB_DBLINK_CONVERTIN',
    'JOB_ACTION',
    'GW_PK_IBPS_DBLINK_IN_CITAD21.GET_IBPS_TBLEXPORT');
END;
/
